import = [
    #"~/.config/alacritty/themes/themes/coolnight.toml"
    #"~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
[window]
padding.x = 7
padding.y = 30

decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15

